### ISSUE TITLE
[question] request for license or attribution information 

### ISSUE THREAD

**Issue by milodubois** [aomlomics/tutorials#13]
Thank you for this instructive material provided. I would like to utilize some contents for training of new students, adding additional material sourced from other "canonical" guides. Kindly, can you please inform how to cite the authors of this material and under what license this material is covered? Finally, kindly inform to what extent this material can be adapted and/or changed and published for use in other (e.g. teaching) contexts.

Regards,
@milodubois

**Comment by lukenoaa** [comment]
Hi @milodubois,

I have added a BSD 3-Clause "New" or "Revised" License to the repository. You are free to adapt or change this material. You may cite the GitHub repository URL if you like. If you create any new content that you think may be useful to others, please feel free to create a pull request against the main repository.

Thanks!
Luke

**Comment by milodubois** [comment]
Thanks @lukenoaa so much for this update. I have a couple of ideas in mind and will work on them, generating a PR for your review in the near future, if you think it to be potentially relevant.
#14 closes this issue.

All the best,
Milo
